ENTRYPOINT ["/entrypoint.sh"]

LABEL "com.github.actions.name"="Deploys to GitHub Pages"
LABEL "com.github.actions.description"="Deploys the project to GitHub Pages"
LABEL "com.github.actions.icon"="globe"
LABEL "com.github.actions.color"="green"

LABEL "repository"="http://github.com/mafiono/Ninecasino-app/tree/gh-pages/deploy"